name: Release
on:
  release:
    types:
      - "created"
jobs:
  release:
    name: Release ${{ matrix.run.target }}
    runs-on: ${{ matrix.run.runner }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        run:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - runner: macos-latest
            target: x86_64-apple-darwin
          - runner: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.run.target }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --target ${{ matrix.run.target }}
      - run: |
          mkdir archive
          if [ "$RUNNER_OS" == "Windows" ]; then
            cp target/${{ matrix.run.target }}/release/patchouli.exe "patchouli.exe"
          else
            cp target/${{ matrix.run.target }}/release/patchouli "patchouli"
          fi
          FILENAME="patchouli-$VERSION-$TARGET.tar.gz"
          tar -czf $FILENAME patchouli* README.md LICENSE
          echo $(sha256sum $FILENAME) > "$FILENAME.sha256"
        shell: bash
        env:
          VERSION: ${{ github.ref_name }}
          TARGET: ${{ matrix.run.target }}
      - uses: softprops/action-gh-release@v1
        with:
          files: patchouli-*

  crates:
    name: Release to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
